"""Versioned API contracts shared by the semantic core and data plane."""

from .semantic_core import (
    AdapterCapabilitiesContract,
    AuthorizationContextContract,
    AuthorizationProjectionContract,
    ConsistencyRequestContract,
    DataPlaneStatusContract,
    DataPlaneCapabilitiesContract,
    ExecutionContextContract,
    MigrationInstructionContract,
    MigrationRequest,
    OntologySourceMappingContract,
    PolicyConditionContract,
    PolicyEvaluateRequest,
    ResultManifestContract,
    SchemaMigrationPlanContract,
    SecurityPolicyContract,
    SecurityPolicyPatch,
    SecurityPolicyRequest,
    SemanticResourceContract,
    SemanticChangeRequest,
    SemanticResourcePayload,
    SemanticSchemaContract,
)

__all__ = [
    "ConsistencyRequestContract",
    "AuthorizationContextContract",
    "AuthorizationProjectionContract",
    "AdapterCapabilitiesContract",
    "ResultManifestContract",
    "DataPlaneStatusContract",
    "DataPlaneCapabilitiesContract",
    "ExecutionContextContract",
    "MigrationInstructionContract",
    "MigrationRequest",
    "OntologySourceMappingContract",
    "PolicyConditionContract",
    "PolicyEvaluateRequest",
    "SecurityPolicyPatch",
    "SecurityPolicyRequest",
    "SecurityPolicyContract",
    "SemanticChangeRequest",
    "SemanticResourcePayload",
    "SemanticResourceContract",
    "SemanticSchemaContract",
    "SchemaMigrationPlanContract",
]
