"""durable what-if scenario catalog and immutable revisions"""
from alembic import op
import sqlalchemy as sa
revision = "0025_scenarios"
down_revision = "0024_query_view_manifest_fields"
branch_labels = None
depends_on = None

def upgrade():
    op.create_table("v2_scenarios", sa.Column("id", sa.String(36), primary_key=True), sa.Column("ontology_id", sa.String(), sa.ForeignKey("ontology_projects.id", ondelete="CASCADE"), nullable=False), sa.Column("owner_id", sa.String(), sa.ForeignKey("users.id"), nullable=False), sa.Column("name", sa.String(200), nullable=False), sa.Column("description", sa.Text(), nullable=False), sa.Column("status", sa.String(20), nullable=False), sa.Column("base_view_id", sa.String(64), sa.ForeignKey("v2_query_data_views.id"), nullable=False), sa.Column("head_revision", sa.Integer(), nullable=False), sa.Column("etag", sa.Integer(), nullable=False), sa.Column("ttl_seconds", sa.Integer()), sa.Column("protected_demo", sa.Boolean(), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False), sa.CheckConstraint("status IN ('active','archived')", name="ck_scenario_status"))
    op.create_index("ix_v2_scenarios_ontology_id", "v2_scenarios", ["ontology_id"]); op.create_index("ix_v2_scenarios_owner_id", "v2_scenarios", ["owner_id"])
    op.create_table("v2_scenario_revisions", sa.Column("id", sa.String(36), primary_key=True), sa.Column("scenario_id", sa.String(36), sa.ForeignKey("v2_scenarios.id", ondelete="CASCADE"), nullable=False), sa.Column("revision", sa.Integer(), nullable=False), sa.Column("parent_revision", sa.Integer()), sa.Column("changeset_id", sa.String(36)), sa.Column("result_view_id", sa.String(64), sa.ForeignKey("v2_query_data_views.id"), nullable=False), sa.Column("logic_manifest_digest", sa.String(128)), sa.Column("content_digest", sa.String(128), nullable=False), sa.Column("status", sa.String(20), nullable=False), sa.Column("error_json", sa.JSON()), sa.Column("created_by", sa.String(), sa.ForeignKey("users.id"), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.UniqueConstraint("scenario_id", "revision", name="uq_scenario_revision"))
    op.create_index("ix_v2_scenario_revisions_scenario_id", "v2_scenario_revisions", ["scenario_id"])
    op.create_table("v2_scenario_changesets", sa.Column("id", sa.String(36), primary_key=True), sa.Column("scenario_id", sa.String(36), sa.ForeignKey("v2_scenarios.id", ondelete="CASCADE"), nullable=False), sa.Column("base_revision", sa.Integer(), nullable=False), sa.Column("ordered_edits", sa.JSON(), nullable=False), sa.Column("payload_hash", sa.String(128), nullable=False), sa.Column("client_request_id", sa.String(200), nullable=False), sa.Column("status", sa.String(20), nullable=False), sa.Column("validation_report", sa.JSON(), nullable=False), sa.Column("actor_id", sa.String(), sa.ForeignKey("users.id"), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.UniqueConstraint("scenario_id", "client_request_id", name="uq_scenario_request"))
    op.create_index("ix_v2_scenario_changesets_scenario_id", "v2_scenario_changesets", ["scenario_id"])
    op.create_table("v2_scenario_runs", sa.Column("id", sa.String(36), primary_key=True), sa.Column("scenario_id", sa.String(36), sa.ForeignKey("v2_scenarios.id", ondelete="CASCADE"), nullable=False), sa.Column("revision", sa.Integer(), nullable=False), sa.Column("case_key", sa.String(120), nullable=False), sa.Column("logic_asset_key", sa.String(160), nullable=False), sa.Column("logic_version", sa.String(40), nullable=False), sa.Column("parameters", sa.JSON(), nullable=False), sa.Column("status", sa.String(20), nullable=False), sa.Column("progress", sa.Integer(), nullable=False), sa.Column("current_stage", sa.String(40), nullable=False), sa.Column("input_digest", sa.String(128)), sa.Column("output_digest", sa.String(128)), sa.Column("error_json", sa.JSON()), sa.Column("cancel_requested", sa.Boolean(), nullable=False), sa.Column("created_by", sa.String(), sa.ForeignKey("users.id"), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False))
    op.create_index("ix_v2_scenario_runs_scenario_id", "v2_scenario_runs", ["scenario_id"])
    op.create_table("v2_scenario_metrics", sa.Column("id", sa.String(36), primary_key=True), sa.Column("run_id", sa.String(36), sa.ForeignKey("v2_scenario_runs.id", ondelete="CASCADE"), nullable=False), sa.Column("metric_key", sa.String(120), nullable=False), sa.Column("baseline", sa.Float()), sa.Column("candidate", sa.Float()), sa.Column("unit", sa.String(40), nullable=False), sa.Column("delta", sa.Float()), sa.Column("completeness", sa.String(20), nullable=False), sa.Column("provenance", sa.JSON(), nullable=False))
    op.create_index("ix_v2_scenario_metrics_run_id", "v2_scenario_metrics", ["run_id"])
    op.create_table("v2_scenario_grants", sa.Column("scenario_id", sa.String(36), sa.ForeignKey("v2_scenarios.id", ondelete="CASCADE"), primary_key=True), sa.Column("principal_id", sa.String(), sa.ForeignKey("users.id"), primary_key=True), sa.Column("role", sa.String(10), nullable=False), sa.CheckConstraint("role IN ('viewer','editor')", name="ck_scenario_grant_role"))
    op.create_table("v2_scenario_audits", sa.Column("id", sa.String(36), primary_key=True), sa.Column("scenario_id", sa.String(36), sa.ForeignKey("v2_scenarios.id", ondelete="CASCADE"), nullable=False), sa.Column("revision", sa.Integer()), sa.Column("run_id", sa.String(36)), sa.Column("actor_id", sa.String(), sa.ForeignKey("users.id"), nullable=False), sa.Column("operation", sa.String(60), nullable=False), sa.Column("summary", sa.JSON(), nullable=False), sa.Column("request_id", sa.String(200)), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False))
    op.create_index("ix_v2_scenario_audits_scenario_id", "v2_scenario_audits", ["scenario_id"])

def downgrade():
    for table in ["v2_scenario_audits", "v2_scenario_grants", "v2_scenario_metrics", "v2_scenario_runs", "v2_scenario_changesets", "v2_scenario_revisions", "v2_scenarios"]:
        op.drop_table(table)
