from alembic import op
import sqlalchemy as sa

revision = '0021_object_sets'
down_revision = '0020_logic_contracts'
branch_labels = None
depends_on = None

def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('v2_object_set_resources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ontology_id', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('lifecycle', sa.String(length=20), nullable=False),
    sa.Column('definition_kind', sa.String(length=20), nullable=False),
    sa.Column('head_version', sa.Integer(), nullable=False),
    sa.Column('etag', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("lifecycle IN ('permanent','temporary')", name='ck_object_set_lifecycle'),
    sa.CheckConstraint("status IN ('active','archived','tombstone')", name='ck_object_set_status'),
    sa.CheckConstraint('head_version >= 1 AND etag >= 1', name='ck_object_set_versions'),
    sa.ForeignKeyConstraint(['ontology_id'], ['ontology_projects.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_v2_object_set_resources_ontology_id'), 'v2_object_set_resources', ['ontology_id'], unique=False)
    op.create_index(op.f('ix_v2_object_set_resources_owner_id'), 'v2_object_set_resources', ['owner_id'], unique=False)
    op.create_table('v2_object_set_audits',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('resource_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.String(), nullable=False),
    sa.Column('operation', sa.String(length=40), nullable=False),
    sa.Column('definition_hash', sa.String(length=64), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['v2_object_set_resources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_v2_object_set_audits_resource_id'), 'v2_object_set_audits', ['resource_id'], unique=False)
    op.create_table('v2_object_set_grants',
    sa.Column('resource_id', sa.String(length=36), nullable=False),
    sa.Column('principal_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.CheckConstraint("role IN ('view','edit')", name='ck_object_set_grant_role'),
    sa.ForeignKeyConstraint(['principal_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['v2_object_set_resources.id'], ),
    sa.PrimaryKeyConstraint('resource_id', 'principal_id')
    )
    op.create_table('v2_object_set_versions',
    sa.Column('resource_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('contract_version', sa.String(length=30), nullable=False),
    sa.Column('definition', sa.JSON(), nullable=False),
    sa.Column('result_type', sa.JSON(), nullable=False),
    sa.Column('definition_hash', sa.String(length=64), nullable=False),
    sa.Column('metadata_digest', sa.String(length=64), nullable=False),
    sa.Column('dependency_manifest', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['v2_object_set_resources.id'], ),
    sa.PrimaryKeyConstraint('resource_id', 'version')
    )
    op.create_table('v2_object_set_dependencies',
    sa.Column('resource_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=False),
    sa.Column('target_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['resource_id', 'version'], ['v2_object_set_versions.resource_id', 'v2_object_set_versions.version'], ),
    sa.ForeignKeyConstraint(['target_id', 'target_version'], ['v2_object_set_versions.resource_id', 'v2_object_set_versions.version'], ),
    sa.PrimaryKeyConstraint('resource_id', 'version', 'target_id', 'target_version')
    )
    op.create_table('v2_object_set_leases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('resource_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('principal_id', sa.String(), nullable=False),
    sa.Column('manifest', sa.JSON(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['principal_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['resource_id', 'version'], ['v2_object_set_versions.resource_id', 'v2_object_set_versions.version'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_v2_object_set_leases_expires_at'), 'v2_object_set_leases', ['expires_at'], unique=False)
    op.create_table('v2_object_set_static_members',
    sa.Column('resource_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('concrete_type', sa.String(length=200), nullable=False),
    sa.Column('object_id', sa.String(length=300), nullable=False),
    sa.ForeignKeyConstraint(['resource_id', 'version'], ['v2_object_set_versions.resource_id', 'v2_object_set_versions.version'], ),
    sa.PrimaryKeyConstraint('resource_id', 'version', 'concrete_type', 'object_id')
    )
    # ### end Alembic commands ###

def downgrade():
    raise RuntimeError('Object Set history is retained; destructive downgrade is not supported')
