import { useEffect, useMemo, useState } from "react";
import { apiClientV2 } from "@/api/client";

type ContextDraft = { objects: any[]; reasoning_run: any; conclusions: any[]; rules: any[]; notice?: string };

const humanize = (value: string) => value.replace(/^FactoryNet:/, "").replace(/[:_/-]+/g, " ").replace(/\b(Phase|ProcessPhase)\s+/i, "工艺阶段 ").replace(/\b(ToolCondition)\s+/i, "刀具状态 ").trim();
const conclusionText = (item: any) => typeof item === "string" ? item : item?.conclusion || "";
const readableConclusion = (item: any) => {
  const text = conclusionText(item); const match = text.match(/^([A-Z_]+)\((.*)\)$/);
  return match ? `${humanize(match[1])}：${match[2].split(",").map((part: string) => humanize(part.trim())).join(" → ")}` : text;
};

export default function AgentDecisionTab({ ontologyId }: { ontologyId: string }) {
  const [task, setTask] = useState("哪些 CNC 设备因为刀具状态异常需要安排人工检查？");
  const [runs, setRuns] = useState<any[]>([]); const [draft, setDraft] = useState<ContextDraft | null>(null);
  const [draftRunId, setDraftRunId] = useState(""); const [selectedObjects, setSelectedObjects] = useState<string[]>([]);
  const [selectedConclusions, setSelectedConclusions] = useState<string[]>([]); const [agentRunId, setAgentRunId] = useState("");
  const [proposal, setProposal] = useState<any>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  useEffect(() => { apiClientV2.get(`/ontologies/${ontologyId}/reasoning/runs`).then((items: any) => setRuns(items || [])).catch((e: any) => setError(e.message || "加载推理运行失败")); }, [ontologyId]);
  const execute = async (fn: () => Promise<void>) => { setBusy(true); setError(""); setNotice(""); try { await fn(); } catch (e: any) { setError(e.detail || e.message || "请求失败"); } finally { setBusy(false); } };
  const selectionSummary = useMemo(() => {
    const objects = (draft?.objects || []).filter(item => selectedObjects.includes(item.id));
    const conclusions = (draft?.conclusions || []).filter(item => selectedConclusions.includes(conclusionText(item)));
    if (!objects.length) return "尚未选择业务对象。";
    const phases = [...new Set(objects.map(item => item.properties?.ctx_process_phase).filter(Boolean))] as string[];
    if (!phases.length) return `已选择 ${objects.length} 个对象和 ${conclusions.length} 条结论。它们通过推理证据相连；是否足以回答问题，还需要核对规则条件。`;
    const explanations = phases.map(phase => phase === "Repositioning" ? "重新定位：调整加工位置的阶段" : /^Layer (\d+) (Up|Down)$/.test(phase) ? phase.replace(/^Layer (\d+) (Up|Down)$/, (_, layer, direction) => `第 ${layer} 层${direction === "Up" ? "向上" : "向下"}加工：区分加工层次和行进方向的步骤名称`) : phase);
    const states = objects.map(item => item.properties?.ctx_tool_condition);
    const condition = states.every(state => state === "unworn") ? "这些记录的刀具状态都标为“未磨损”。它们不能支持“已发现刀具磨损”的判断，但也不能证明设备不存在其他异常，或其他时段同样正常。" : "刀具状态请逐条核对；状态标签本身不等于是否需要检查的结论。";
    return `本次选出的 ${objects.length} 条记录，能帮助核对加工步骤与刀具状态，而不是因为它们已经被判定异常才入选。涉及的步骤是：${explanations.join("；")}。这些是工艺步骤名称，不是故障等级。当前选中 ${conclusions.length} 条规则结论，用于把记录中的状态对应到加工阶段。${condition}`;
  }, [draft, selectedObjects, selectedConclusions]);
  const createDraft = () => execute(async () => { const out: any = await apiClientV2.post(`/ontologies/${ontologyId}/agent/context-drafts`, { task }); const context = out.context as ContextDraft; setAgentRunId(out.run_id); setDraft(context); setDraftRunId(context.reasoning_run?.id || ""); setSelectedObjects((context.objects || []).map((item) => item.id)); setSelectedConclusions((context.conclusions || []).map(conclusionText).filter(Boolean)); setProposal(null); setNotice("上下文草案已生成。当前采用关键词与证明匹配，请审核后批准。"); });
  const changeRun = (runId: string) => execute(async () => {
    setProposal(null);
    const context: any = await apiClientV2.post(`/ontologies/${ontologyId}/agent/context-preview`, { object_ids: selectedObjects, reasoning_run_id: runId });
    setDraftRunId(runId); setDraft(context); setSelectedConclusions(context.conclusions.map(conclusionText));
  });
  const approveContext = () => execute(async () => { await apiClientV2.patch(`/ontologies/${ontologyId}/agent/runs/${agentRunId}/context`, { object_ids: selectedObjects, reasoning_run_id: draftRunId, conclusions: selectedConclusions }); const out: any = await apiClientV2.post(`/ontologies/${ontologyId}/agent/runs/${agentRunId}/generate`, {}); setProposal(out.proposal); setNotice("上下文已批准，Agent 已生成决策建议。请查看证据后确认保存。"); });
  const confirmDecision = () => execute(async () => { await apiClientV2.post(`/ontologies/${ontologyId}/agent/runs/${agentRunId}/confirm`, {}); setNotice("决策已确认并保存，可在“决策与影响链”中查看。"); });
  return <div className="space-y-4">
    <section className="rounded border bg-white p-5"><h2 className="text-xl font-semibold">Agent 决策助手</h2><p className="mt-2 text-sm text-slate-600">用自然语言提问，系统先匹配对象、命中规则和推理证据；你批准上下文后，它才生成正式建议。</p><textarea aria-label="自然语言问题" className="mt-4 w-full rounded border p-3 text-sm" rows={3} value={task} onChange={(e) => setTask(e.target.value)} /><button disabled={busy || task.trim().length < 5} className="mt-3 rounded bg-slate-900 px-4 py-2 text-sm text-white disabled:opacity-50" onClick={createDraft}>分析问题并选择上下文</button></section>
    {draft && <section className="rounded border border-violet-200 bg-violet-50/30 p-5"><h2 className="font-semibold">Agent 上下文草案</h2><p className="mt-1 text-sm text-slate-600">请审核对象 → 命中规则 → 推理运行 → 实际结论。</p><div className="mt-4 space-y-4">
      <div className="rounded border border-violet-200 bg-white p-4 text-sm"><h3 className="font-semibold">这些材料为什么值得看？</h3><p className="mt-2 leading-7 text-slate-700">{selectionSummary}</p></div><div><h3 className="text-sm font-medium">相关业务对象 / 证明引用的观测</h3>{draft.objects.length === 0 && <p className="mt-1 text-sm text-amber-700">未自动找到对象，请重新提问。</p>}<div className="mt-2 grid gap-2 md:grid-cols-2">{draft.objects.map((item) => <label key={item.id} className="rounded border bg-white p-3 text-sm"><input type="checkbox" className="mr-2" checked={selectedObjects.includes(item.id)} onChange={(e) => setSelectedObjects((old) => e.target.checked ? [...old, item.id] : old.filter((id) => id !== item.id))} /><strong>{item.label || item.id}</strong><p className="mt-1 text-xs text-slate-700">{item.summary}</p><details className="mt-2 text-xs text-slate-500"><summary>查看技术详情</summary><pre className="mt-1 whitespace-pre-wrap">{JSON.stringify({ matching_reason: item.relevance, properties: item.properties }, null, 2)}</pre></details></label>)}</div></div>
      <div className="rounded border bg-white p-3 text-sm"><h3 className="font-medium">命中规则</h3>{(draft.rules || []).map((rule: any) => <div key={rule.id} className="mt-2"><p className="leading-7">{rule.explanation}</p><details className="mt-1 text-xs text-slate-500"><summary>查看技术详情</summary><p>{rule.id} · {rule.status}</p><pre className="mt-1 whitespace-pre-wrap">{rule.technical_rule}</pre></details></div>)}</div>
      <div><h3 className="text-sm font-medium">推理运行</h3><select aria-label="上下文推理运行" className="mt-2 w-full rounded border bg-white p-2 text-sm" value={draftRunId} onChange={(e) => changeRun(e.target.value)}><option value="">请选择推理运行</option>{runs.map((run) => <option key={run.run_id} value={run.run_id}>{run.created_at} · {run.status} · {run.derived_fact_count} 条结论</option>)}</select></div>
      <div><h3 className="text-sm font-medium">推理结论</h3><div className="mt-2 space-y-2">{(draft.conclusions || []).map((item) => { const value = conclusionText(item); return <label key={value} className="block rounded border bg-white p-3 text-sm"><input type="checkbox" className="mr-2" checked={selectedConclusions.includes(value)} onChange={(e) => setSelectedConclusions((old) => e.target.checked ? [...old, value] : old.filter((v) => v !== value))} /><strong>{item.human_explanation || readableConclusion(item)}</strong><details className="mt-2 ml-6 text-xs text-slate-500"><summary>查看技术详情（供审计使用）</summary><p className="mt-1">系统原始结论：{value}</p><pre className="mt-1 whitespace-pre-wrap">{JSON.stringify({ relevance: item.relevance, limitation: item.limitation, rule_id: item.rule_id, premises: item.premises, bindings: item.bindings }, null, 2)}</pre></details></label>; })}</div></div>
    </div><button disabled={busy || !agentRunId || !draftRunId || !selectedConclusions.length} className="mt-4 rounded bg-violet-700 px-4 py-2 text-sm text-white disabled:opacity-50" onClick={approveContext}>批准上下文并生成建议</button></section>}
    {error && <p role="alert" className="rounded border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</p>}{notice && <p role="status" className="rounded border border-violet-200 bg-violet-50 p-3 text-sm text-violet-800">{notice}</p>}
    {proposal && <section className="rounded border bg-white p-5"><h2 className="font-semibold">决策建议（待确认）</h2><p className="mt-2"><strong>建议：</strong>{proposal.outcome}</p><p className="mt-2 text-sm">{proposal.reasoning}</p><div className="mt-3 rounded bg-slate-50 p-3 text-sm"><strong>为什么这样建议：</strong><p className="mt-1">{proposal.reasoning}</p>{proposal.decision_rule_evaluation && <div className="mt-3 border-t pt-3"><strong>决策规则核对</strong><p className="mt-1">检查了 {proposal.decision_rule_evaluation.rule_count} 条已发布规则；命中 {proposal.decision_rule_evaluation.matches.length} 条。</p>{(proposal.decision_rule_evaluation.evaluated || []).map((item: any) => <div key={item.rule_id} className="mt-2 rounded border bg-white p-2"><strong>{item.name}</strong><span className="ml-2 rounded bg-slate-100 px-2 py-0.5 text-xs">{item.status}</span><p className="mt-1">{item.explanation}</p><p className="mt-1 text-xs text-slate-600">{item.objects.flatMap((obj: any) => obj.alternatives.flatMap((alt: any) => alt.checks)).map((check: any) => `${check.field}: ${check.missing ? "缺少数据" : check.actual}（条件 ${check.expected}，${check.missing ? "未验证" : check.passed ? "满足" : "未满足"}）`).join("；")}</p></div>)}</div>}<strong className="mt-3 block">依据解释：</strong>{(proposal.evidence || proposal.basis || []).map((item: any) => <p key={item.conclusion} className="mt-1">{item.human_explanation || readableConclusion(item.conclusion)}</p>)}</div><details className="mt-3"><summary className="cursor-pointer text-sm text-violet-700">查看规则和证据（技术详情）</summary><pre className="mt-2 max-h-80 overflow-auto whitespace-pre-wrap rounded bg-slate-50 p-3 text-xs">{JSON.stringify({ basis: proposal.basis, evidence: proposal.evidence, ontology_revision_id: proposal.ontology_revision_id, agent_run_id: agentRunId }, null, 2)}</pre></details><button disabled={busy} className="mt-4 rounded bg-violet-700 px-4 py-2 text-sm text-white disabled:opacity-50" onClick={confirmDecision}>确认并保存决策</button></section>}
  </div>;
}
